/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Life: typeof import('./src/components/Life.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    SkillCard: typeof import('./src/components/SkillCard.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
  }
}
